/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import backend.Admin;
import backend.Client;
import backend.Gestionnaire;

/**
 *
 * @author alaaeddine
 */
public class Clients extends javax.swing.JPanel {
	public static Connection conn;
    /**
     * Creates new form NewJPanel1
     */
    public Clients() {
        initComponents();
        try {
            conn = backend.ConnectionManager.getConnection();
			populateTableFromArrayList(Client.getAllClients(conn));
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        telephoneLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        nomTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        numeroPermisLabel = new javax.swing.JLabel();
        numeroPermisTF = new javax.swing.JTextField();
        prenomTF = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        telephoneTF = new javax.swing.JTextField();
        enregistrerBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        supprimerBTN = new javax.swing.JButton();
        rechercherBTN = new javax.swing.JButton();
        modifierBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 231, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setForeground(new java.awt.Color(210, 231, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(210, 231, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 624));

        jPanel4.setBackground(new java.awt.Color(210, 231, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 84, 129), 2, true), "Informations du client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        telephoneLabel.setText("Telephone:");

        nomLabel.setText("Nom:");

        numeroPermisLabel.setText("Numero permis:");

        emailLabel.setText("Email:");

        prenomLabel.setText("Prenom:");

        enregistrerBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        enregistrerBTN.setForeground(new java.awt.Color(16, 84, 129));
        enregistrerBTN.setText("Enregistrer");
        enregistrerBTN.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                if(telephoneTF.getText().isEmpty() || nomTF.getText().isEmpty() || prenomTF.getText().isEmpty() || emailTF.getText().isEmpty()) {
                	JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs de texte.", "Error", JOptionPane.ERROR_MESSAGE);
                }else {
                    try {
                        conn = backend.ConnectionManager.getConnection();
                        Client client = new Client(conn, nomTF.getText(), prenomTF.getText(), Integer.parseInt(telephoneTF.getText()), emailTF.getText(), Integer.parseInt(numeroPermisTF.getText()));
                        populateTable();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
       	}
        	
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telephoneLabel)
                    .addComponent(numeroPermisLabel)
                    .addComponent(prenomLabel)
                    .addComponent(nomLabel)
                    .addComponent(emailLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enregistrerBTN)
                    .addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroPermisTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLabel)
                    .addComponent(prenomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneLabel)
                    .addComponent(telephoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPermisLabel)
                    .addComponent(numeroPermisTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(enregistrerBTN)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(210, 231, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 624));

        jPanel5.setBackground(new java.awt.Color(210, 231, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Clients enrégistres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_client", "Nom", "Prénom", "Téléphone", "Email", "Numéro Permis"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(16, 84, 129));
        jScrollPane1.setViewportView(jTable1);

        supprimerBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        supprimerBTN.setForeground(new java.awt.Color(16, 84, 129));
        supprimerBTN.setText("Supprimer");
        supprimerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBTNActionPerformed(evt);
            }
        });

        rechercherBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        rechercherBTN.setForeground(new java.awt.Color(16, 84, 129));
        rechercherBTN.setText("Rechercher");
        rechercherBTN.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		rechercherBTNActionPerformed(evt);
        	}
        });

        modifierBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        modifierBTN.setForeground(new java.awt.Color(16, 84, 129));
        modifierBTN.setText("Modifier");
        modifierBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(rechercherBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(modifierBTN)
                .addGap(83, 83, 83)
                .addComponent(supprimerBTN)
                .addGap(85, 85, 85))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercherBTN)
                    .addComponent(supprimerBTN)
                    .addComponent(modifierBTN))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    protected void rechercherBTNActionPerformed(ActionEvent evt) {
    	new searchClient(this, conn).setVisible(true);
	}

	private void modifierBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBTNActionPerformed
		int selectedRow = jTable1.getSelectedRow();
    	Object value = jTable1.getValueAt(selectedRow, 0);
    	new ModifyClient(this, conn, Integer.parseInt(value.toString())).setVisible(true);
   }//GEN-LAST:event_modifierBTNActionPerformed

    private void supprimerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBTNActionPerformed
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();

        // Check if a row is selected
        if (selectedRow != -1) {
            // Get the value in the first column (index 0) of the selected row
            Object value = jTable1.getValueAt(selectedRow, 0);

            // Display a confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this user?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            // If user confirms deletion
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    int id = Integer.parseInt(value.toString());
                    Client.deleteClient(conn, id);
                    populateTable(); // Refresh the table
                    JOptionPane.showMessageDialog(this, "User deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error deleting user: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Warn the user to select a row
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a user to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
            );
        }
   
    }//GEN-LAST:event_supprimerBTNActionPerformed

    public void populateTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data
        try {
            conn = backend.ConnectionManager.getConnection();
            String query = "SELECT * FROM Client";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_client"),
                    rs.getString("nom"),
                    rs.getString("prenom"),
                    rs.getInt("telephone"),
                    rs.getString("email"),
                    rs.getString("numero_permis")
                };
                model.addRow(row);
            }
            System.out.println("Table populated successfully!");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void populateTableFromArrayList(ArrayList<Client> clients) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Client client : clients) {
            Object[] row = {
            		client.getIdClient(),
            		client.getNom(),
            		client.getPrenom(),
            		client.getTelephone(),
            		client.getEmail(),
            		client.getNumeroPermis()
            };
            model.addRow(row);
        }
        System.out.println("Table populated successfully!");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton enregistrerBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifierBTN;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomTF;
    private javax.swing.JLabel numeroPermisLabel;
    private javax.swing.JTextField numeroPermisTF;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField prenomTF;
    private javax.swing.JButton rechercherBTN;
    private javax.swing.JButton supprimerBTN;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTF;
    // End of variables declaration//GEN-END:variables
}
