package frontend;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template // Note: Template comment still says JPanel
 */
// Add necessary imports
import javax.swing.*; // Includes JFrame, JScrollPane, JTable, SwingConstants, etc.
import javax.swing.table.DefaultTableModel; // Import DefaultTableModel
import java.sql.*; // Includes Connection, Statement, ResultSet, SQLException

/**
 *
 * @author alaaeddine
 */
// Ensure the class extends JFrame
public class Historique extends javax.swing.JFrame {
    Connection conn;

    /**
     * Creates new form Historique (Default constructor)
     * This constructor will attempt to get its own connection or handle the case where none is provided.
     */
    public Historique() {
        // Call the other constructor with a null connection
        // This allows reusing the initialization logic
        this(null);
    }

    /**
     * Creates new form Historique with a specific database connection.
     * @param conn The database connection to use. Can be null.
     */
    public Historique(Connection conn) {
        this.conn = conn; // Store the connection
        // Initialize the GUI components generated by NetBeans Matisse
        initComponents();

        // --- JFrame specific setup ---
        // Set the window title
        setTitle("Historique des Réservations");
        // Define what happens when the user clicks the 'X' button
        // DISPOSE_ON_CLOSE closes only this window. EXIT_ON_CLOSE exits the whole application.
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // Add the main panel (jPanel1) created by initComponents to the JFrame's content pane
        // This is the standard way to add the main GUI container to a JFrame.
        getContentPane().add(jPanel1);
        setLocationRelativeTo(null);
        // Pack the window to fit the preferred size of its components
        pack();
        // Make the window visible on the screen
        // setVisible(true) is typically called last in the constructor after setup
        // setVisible(true); // Moved to main method or after constructor for better control if needed
        // --- End JFrame setup ---

        // --- Populate the table ---
        // Try to populate the table with data from the database
        try {
            populateTable();
        } catch (SQLException sqle) {
            // Print the stack trace for debugging
            sqle.printStackTrace();
            // Optionally, show an error message to the user
            JOptionPane.showMessageDialog(this, "Error loading data: " + sqle.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        // Make the frame visible after attempting to populate (or even if it fails)
        setVisible(true);
    }

    /**
     * Main method to launch the Historique application as a standalone program.
     * This is the entry point when you run the program.
     * @param args Command-line arguments (not used here).
     */
    public static void main(String[] args) {
        // Use SwingUtilities.invokeLater for thread safety.
        // GUI updates should happen on the Event Dispatch Thread (EDT).
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    // Create an instance of Historique.
                    // It will use its default constructor, which calls the other one with null conn.
                    // The constructor handles getting the connection (via populateTable) and making the frame visible.
                    new Historique();
                } catch (Exception e) {
                    // Catch any unexpected exceptions during startup
                    e.printStackTrace();
                    // Show an error dialog if startup fails
                    JOptionPane.showMessageDialog(null, "Failed to start Historique application: " + e.getMessage(), "Startup Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor (NetBeans Matisse).
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        // Remove or comment out the setLayout for the Historique instance itself,
        // as JFrame content panes have a default BorderLayout.
        // setBackground(new java.awt.Color(210, 231, 255));
        // setLayout(new java.awt.BorderLayout()); // Not needed for JFrame instance

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setForeground(new java.awt.Color(210, 231, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        TabPanel.setBackground(new java.awt.Color(210, 231, 255));
        TabPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(210, 231, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(28, 304));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 28, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 545, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(210, 231, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(30, 304));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel7.setBackground(new java.awt.Color(210, 231, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1274, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1254, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 60, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel11.setBackground(new java.awt.Color(210, 231, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Historiqe des reservations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(1254, 200));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String [] {
                        "idReservation ", "idClient", "idVehicule", "date debut", "date fin", "montant", "statut"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        //jTable2.setPreferredSize(new java.awt.Dimension(1250, 200));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel1.add(TabPanel, java.awt.BorderLayout.CENTER);

        // Remove or comment out the add() call for jPanel1 to the Historique instance itself,
        // because we add jPanel1 to the JFrame's content pane in the constructor.
        // add(jPanel1, java.awt.BorderLayout.CENTER); // Handled in constructor

        // If you need a layout for the JFrame itself (though content pane's default BorderLayout usually suffices),
        // you would set it on getContentPane(), but it's generally not necessary unless changing from the default.
        // getContentPane().setLayout(new BorderLayout()); // Usually not needed if adding one main panel

    }// </editor-fold>//GEN-END:initComponents

    /**
     * Populates the jTable2 with data fetched from the database.
     * @throws SQLException if a database access error occurs.
     */
    public void populateTable() throws SQLException {
        // Get the table model associated with jTable2
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        // Clear any existing rows in the table model
        model.setRowCount(0);

        // Try-with-resources to ensure resources are closed
        try (
                // Attempt to get a database connection if one wasn't passed in or is null
                Connection localConn = (this.conn != null) ? this.conn : backend.ConnectionManager.getConnection();
                // Create a statement for executing the query
                Statement stmt = localConn.createStatement();
                // Execute the query and get the result set
                ResultSet rs = stmt.executeQuery("SELECT * FROM Reservation");
        ) {
            // Iterate through the result set
            while (rs.next()) {
                // Create an array of Objects representing a row of data
                Object[] row = {
                        rs.getInt("id_reservation"),
                        rs.getInt("id_client"),
                        rs.getInt("id_vehicule"),
                        rs.getString("date_debut"),
                        rs.getString("date_fin"),
                        rs.getObject("montant_total"), // Use getObject if type might vary or is nullable
                        rs.getString("statut")
                };
                // Add the row to the table model
                model.addRow(row);
            }
            // Print a success message to the console
            System.out.println("Table populated successfully!");
        } catch (SQLException ex) {
            // Print the stack trace for debugging
            ex.printStackTrace();
            // Re-throw the SQLException so the calling method (constructor) can handle it
            throw ex;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TabPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}