/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Vehicule;

import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author alaaeddine
 */
public class ModifyVehicule extends javax.swing.JFrame {
    Vehicules vehicule;
    Connection conn;
    Vehicule vehic;
    static int id_vehicule;
    /**
     * Creates new form ModifyVehicule
     */
    public ModifyVehicule() {
        initComponents();
    }

    public ModifyVehicule(Vehicules vehicule, Connection conn, int id_vehicule) {
        initComponents();
        this.vehicule = vehicule;
        this.conn = conn;
        ModifyVehicule.id_vehicule = id_vehicule;
    try {
        vehic = Vehicule.getVehicule(conn, id_vehicule);
        marqueTF.setText(vehic.getMarque());
        TypeCB.setSelectedItem(vehic.getType());
        prixLocationJourTF.setText(String.valueOf(vehic.getPrixLocationJour()));
        modeleTF.setText(String.valueOf(vehic.getModele()));
        anneeTF.setText(String.valueOf(vehic.getAnnee()));
    } catch (SQLException e) {
        e.printStackTrace();
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        marqueLabel = new javax.swing.JLabel();
        marqueTF = new javax.swing.JTextField();
        prixLocationJourTF = new javax.swing.JTextField();
        numeroPermisLabel = new javax.swing.JLabel();
        modeleTF = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        anneeTF = new javax.swing.JTextField();
        enregistrerBTN = new javax.swing.JButton();
        TypeCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        jPanel4.setBackground(new java.awt.Color(210, 231, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 84, 129), 2, true), "Informations du vehicule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        typeLabel.setText("Année:");

        marqueLabel.setText("Marque:");

        numeroPermisLabel.setText("Type:");

        emailLabel.setText("Prix location/jour:");

        prenomLabel.setText("Modèle");

        enregistrerBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        enregistrerBTN.setForeground(new java.awt.Color(16, 84, 129));
        enregistrerBTN.setText("Enregistrer");
        enregistrerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerBTNActionPerformed(evt);
            }
        });

        TypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essence", "Diesel", "GPL", "GNV", "Electricité" }));
        TypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeLabel)
                    .addComponent(numeroPermisLabel)
                    .addComponent(prenomLabel)
                    .addComponent(marqueLabel)
                    .addComponent(emailLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(marqueTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(modeleTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(anneeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(prixLocationJourTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(TypeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(enregistrerBTN)
                .addGap(189, 189, 189))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marqueLabel)
                    .addComponent(marqueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLabel)
                    .addComponent(modeleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(anneeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPermisLabel)
                    .addComponent(TypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(prixLocationJourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(enregistrerBTN)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerBTNActionPerformed
        try {
            Connection conn = backend.ConnectionManager.getConnection();
            Vehicule.modifierVehicule(conn, id_vehicule, marqueTF.getText(), modeleTF.getText(), Integer.parseInt(anneeTF.getText()), (String) TypeCB.getSelectedItem(), vehic.getCarburant(), Integer.parseInt(prixLocationJourTF.getText()), vehic.getEtat());
            vehicule.populateTable();
            dispose();
        } catch (SQLException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_enregistrerBTNActionPerformed

    private void TypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TypeCB;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField prixLocationJourTF;
    private javax.swing.JButton enregistrerBTN;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel marqueLabel;
    private javax.swing.JTextField marqueTF;
    private javax.swing.JLabel numeroPermisLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField modeleTF;
    private javax.swing.JTextField anneeTF;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
