/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.*;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Locale;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import backend.Client;
import backend.Reservation;
import backend.Vehicule;

/**
 *
 * @author alaaeddine
 */
public class Reservations extends javax.swing.JPanel {
	static Connection conn;

	backend.Client cli;
	backend.Vehicule vehic;
    long daysBetween;
    /**
     * Creates new form NewJPanel1
     */
    public Reservations() {
        initComponents();
        
        populateClientComboBox(clientCB);
        populateVehiculeComboBox(vehiculeCB);
        try {
            populateTable();
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Dates = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateDTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateFTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dureeTF = new javax.swing.JLabel();
        dureeLabel = new javax.swing.JLabel();
        enregistrerButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Client = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clientNameLabel = new javax.swing.JLabel();
        prenomClient = new javax.swing.JLabel();
        id_clientLabel = new javax.swing.JLabel();
        clientCB = new javax.swing.JComboBox<>();
        nomC = new javax.swing.JLabel();
        clientPrenomLabel = new javax.swing.JLabel();
        Vehicule = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        marqueLabel = new javax.swing.JLabel();
        prix = new javax.swing.JLabel();
        id_vehiculeLabel = new javax.swing.JLabel();
        vehiculeCB = new javax.swing.JComboBox<>();
        marque = new javax.swing.JLabel();
        prixLabel = new javax.swing.JLabel();
        TabPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(210, 231, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setForeground(new java.awt.Color(210, 231, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(210, 231, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(1245, 320));
        jPanel6.setLayout(new java.awt.BorderLayout());

        Dates.setBackground(new java.awt.Color(210, 231, 255));

        jPanel3.setBackground(new java.awt.Color(210, 231, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Information supplementaires de reservation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        jLabel5.setText("Duree:");

        jLabel2.setText("Date fin:");

        dateDTF.setText("2023-12-31");
        dateDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Date debut:");

        dateFTF.setText("2014-12-31");
        dateFTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFTFActionPerformed(evt);
            }
        });

        jLabel3.setText("Prix estimee:");

        dureeTF.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        dureeTF.setForeground(new java.awt.Color(16, 84, 129));
        dureeTF.setText("...");

        dureeLabel.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        dureeLabel.setForeground(new java.awt.Color(16, 84, 129));
        dureeLabel.setText("...");

        enregistrerButton.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        enregistrerButton.setForeground(new java.awt.Color(16, 84, 129));
        enregistrerButton.setText("Enregistrer");
        enregistrerButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
                    conn = backend.ConnectionManager.getConnection();
                    Reservation res = new Reservation(conn, cli, vehic, LocalDate.parse(dateDTF.getText()), LocalDate.parse(dateFTF.getText()));
                    populateTable();
                } catch (SQLException sqle) {
                    sqle.printStackTrace();
                }
        	}
        });

        clientCB.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				try {
                    Client c = backend.Client.getClient(conn, Integer.parseInt(clientCB.getSelectedItem().toString()));
                    cli = c;
                    clientNameLabel.setText(c.getNom());
                    clientPrenomLabel.setText(c.getPrenom());
                } catch (SQLException sqle) {
                    sqle.printStackTrace();
                }

				
			}
        });
        vehiculeCB.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
                try {
                    backend.Vehicule v = backend.Vehicule.getVehicule(conn, Integer.parseInt(vehiculeCB.getSelectedItem().toString()));
                    vehic = v;
                    marqueLabel.setText(v.getMarque());
                    prixLabel.setText(String.valueOf(v.getPrixLocationJour()));
                } catch (SQLException sqle) {
                    sqle.printStackTrace();
                }
			}
        });
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(dureeLabel)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(dureeTF)
                .addGap(125, 125, 125))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(enregistrerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(dureeTF)
                    .addComponent(jLabel5)
                    .addComponent(dureeLabel)
                    .addComponent(dateFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(enregistrerButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout DatesLayout = new javax.swing.GroupLayout(Dates);
        Dates.setLayout(DatesLayout);
        DatesLayout.setHorizontalGroup(
            DatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        DatesLayout.setVerticalGroup(
            DatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.add(Dates, java.awt.BorderLayout.PAGE_END);

        jPanel9.setBackground(new java.awt.Color(210, 231, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        Client.setBackground(new java.awt.Color(210, 231, 255));
        Client.setPreferredSize(new java.awt.Dimension(622, 220));

        jPanel2.setBackground(new java.awt.Color(210, 231, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Selection du client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        clientNameLabel.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        clientNameLabel.setForeground(new java.awt.Color(16, 84, 129));
        clientNameLabel.setText("...");
        

        prenomClient.setText("Prenom:");

        id_clientLabel.setText("id_client:");

        nomC.setText("Nom:");

        clientPrenomLabel.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        clientPrenomLabel.setForeground(new java.awt.Color(16, 84, 129));
        clientPrenomLabel.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prenomClient)
                    .addComponent(nomC)
                    .addComponent(id_clientLabel))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientPrenomLabel)
                            .addComponent(clientNameLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(clientCB, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_clientLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomC)
                    .addComponent(clientNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomClient)
                    .addComponent(clientPrenomLabel))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout ClientLayout = new javax.swing.GroupLayout(Client);
        Client.setLayout(ClientLayout);
        ClientLayout.setHorizontalGroup(
            ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ClientLayout.setVerticalGroup(
            ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel9.add(Client, java.awt.BorderLayout.LINE_START);

        Vehicule.setBackground(new java.awt.Color(210, 231, 255));

        jPanel4.setBackground(new java.awt.Color(210, 231, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Selection du client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        marqueLabel.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        marqueLabel.setForeground(new java.awt.Color(16, 84, 129));
        marqueLabel.setText("...");

        prix.setText("Prix/jour:");

        id_vehiculeLabel.setText("id_vehicule:");

        marque.setText("Marque:");

        prixLabel.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        prixLabel.setForeground(new java.awt.Color(16, 84, 129));
        prixLabel.setText("...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prix)
                    .addComponent(marque)
                    .addComponent(id_vehiculeLabel))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prixLabel)
                            .addComponent(marqueLabel)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(vehiculeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiculeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_vehiculeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marque)
                    .addComponent(marqueLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix)
                    .addComponent(prixLabel))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout VehiculeLayout = new javax.swing.GroupLayout(Vehicule);
        Vehicule.setLayout(VehiculeLayout);
        VehiculeLayout.setHorizontalGroup(
            VehiculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiculeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        VehiculeLayout.setVerticalGroup(
            VehiculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiculeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel9.add(Vehicule, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        TabPanel.setBackground(new java.awt.Color(210, 231, 255));
        TabPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(210, 231, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(28, 304));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(210, 231, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(30, 304));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel7.setBackground(new java.awt.Color(210, 231, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1274, 60));

        jButton1.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 84, 129));
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(16, 84, 129));
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jButton3.setForeground(new java.awt.Color(16, 84, 129));
        jButton3.setText("Retour");
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jButton4.setForeground(new java.awt.Color(16, 84, 129));
        jButton4.setText("Historique");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(157, 157, 157)
                .addComponent(jButton2)
                .addGap(157, 157, 157)
                .addComponent(jButton3)
                .addGap(157, 157, 157)
                .addComponent(jButton4)
                .addGap(142, 142, 142))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TabPanel.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel11.setBackground(new java.awt.Color(210, 231, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Listes de reservations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(1254, 200));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idReservation ", "idClient", "idVehicule", "date debut", "date fin", "montant", "statut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        //jTable2.setPreferredSize(new java.awt.Dimension(1250, 200));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );

        TabPanel.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel1.add(TabPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(ActionEvent evt) {
        // Get the selected row index
        int selectedRow = jTable2.getSelectedRow();

        // Check if a row is selected
        if (selectedRow != -1) {
            // Get the value in the first column (index 0) of the selected row
            String value = jTable2.getValueAt(selectedRow, 0).toString();
            try {
                Reservation curr = Reservation.getReservation(conn, Integer.parseInt(value));
                new Retours(conn, curr, this).setVisible(true);
            } catch (SQLException sqle) {
                sqle.printStackTrace();
            }
        }
    }

    private void jButton2ActionPerformed(ActionEvent evt) {
        // Get the selected row index
        int selectedRow = jTable2.getSelectedRow();

        // Check if a row is selected
        if (selectedRow != -1) {
            // Get the value in the first column (index 0) of the selected row
            Object value = jTable2.getValueAt(selectedRow, 0);

            // Display a confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this reservation?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            // If user confirms deletion
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    int id = Integer.parseInt(value.toString());
                    Reservation toDelete = backend.Reservation.getReservation(conn, id);
                    backend.Reservation.annulerReservation(conn, toDelete);
                    populateTable(); // Refresh the table
                    JOptionPane.showMessageDialog(this, "Reservation deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error deleting vehicule: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Warn the user to select a row
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a reservation to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }

    private void dateFTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFTFActionPerformed
        LocalDate startDate = LocalDate.parse(dateDTF.getText());
        LocalDate endDate = LocalDate.parse(dateFTF.getText());
        if (startDate.isBefore(endDate) && endDate.isAfter(startDate)) {
            daysBetween = ChronoUnit.DAYS.between(startDate, endDate);
            dureeLabel.setText(String.valueOf(daysBetween));
            dureeTF.setText(String.valueOf(daysBetween * vehic.getPrixLocationJour()));
        }
    }//GEN-LAST:event_dateFTFActionPerformed

    private void dateDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDTFActionPerformed
        LocalDate startDate = LocalDate.parse(dateDTF.getText());
        LocalDate endDate = LocalDate.parse(dateFTF.getText());
        if (startDate.isBefore(endDate) && endDate.isAfter(startDate)) {
            daysBetween = ChronoUnit.DAYS.between(startDate, endDate);
            dureeLabel.setText(String.valueOf(daysBetween));
            dureeTF.setText(String.valueOf(daysBetween * vehic.getPrixLocationJour()));
        }


    }//GEN-LAST:event_dateDTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "NET Beans stopped working and i forgot to design this window so...\nModifying Reservation by calling the appropriate function from the backend's 'Reservation' class works just fine though.");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateClientComboBox(JComboBox<String> comboBox) {
        comboBox.removeAllItems(); // Clear existing items
        try {
            conn = backend.ConnectionManager.getConnection();
            String query = "SELECT * FROM Client";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                comboBox.addItem(rs.getString("id_client")); // add each name to the combo box
            }
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }
    }
    
    public void populateVehiculeComboBox(JComboBox<String> comboBox) {
        comboBox.removeAllItems(); // Clear existing items
        try {
            conn = backend.ConnectionManager.getConnection();
            String query = "SELECT * FROM Vehicule";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                comboBox.addItem(rs.getString("id_vehicule")); // add each name to the combo box
            }
        } catch (SQLException sqle) {
            sqle.printStackTrace();
        }
    }
    
    public void populateTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing data
        try {
            conn = backend.ConnectionManager.getConnection();
            String query = "SELECT * FROM Reservation";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_reservation"),
                    rs.getInt("id_client"),
                    rs.getInt("id_vehicule"),
                    rs.getString("date_debut"),
                    rs.getString("date_fin"),
                    rs.getInt("montant_total"),
                    rs.getString("statut")
                };
                model.addRow(row);
            }
            System.out.println("Table populated successfully!");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void populateTableFromArrayList(ArrayList<Reservation> reservations) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing data

        for (Reservation reservation : reservations) {
            Object[] row = {
            		Integer.toString(reservation.getIdReservation()),
            		Integer.toString(reservation.client.getIdClient()),
            		Integer.toString(reservation.vehicule.getIdVehicle()),
            		reservation.getDateDebut().toString(),
            		reservation.getDateFin().toString(),
            		reservation.getMontantTotal(),
            		reservation.getStatut()
            };
            model.addRow(row);
        }
        System.out.println("Table populated successfully!");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Client;
    private javax.swing.JPanel Dates;
    private javax.swing.JPanel TabPanel;
    private javax.swing.JPanel Vehicule;
    private javax.swing.JComboBox<String> clientCB;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JLabel clientPrenomLabel;
    private javax.swing.JTextField dateDTF;
    private javax.swing.JTextField dateFTF;
    private javax.swing.JLabel dureeLabel;
    private javax.swing.JLabel dureeTF;
    private javax.swing.JButton enregistrerButton;
    private javax.swing.JLabel id_clientLabel;
    private javax.swing.JLabel id_vehiculeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel marque;
    private javax.swing.JLabel marqueLabel;
    private javax.swing.JLabel nomC;
    private javax.swing.JLabel prenomClient;
    private javax.swing.JLabel prix;
    private javax.swing.JLabel prixLabel;
    private javax.swing.JComboBox<String> vehiculeCB;
    // End of variables declaration//GEN-END:variables
}
