/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import backend.Client;
import backend.Vehicule;

/**
 *
 * @author alaaeddine
 */
public class Vehicules extends javax.swing.JPanel {
	static Connection conn;
	
    /**
     * Creates new form NewJPanel1
     */
    public Vehicules() {
        initComponents();
        try {
            conn = backend.ConnectionManager.getConnection();
            populateTableFromArrayList(Vehicule.afficherVehicule(conn));
		} catch (SQLException e) { 
			e.printStackTrace();
		}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        marqueLabel = new javax.swing.JLabel();
        marqueTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        numeroPermisLabel = new javax.swing.JLabel();
        prenomTF = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        telephoneTF = new javax.swing.JTextField();
        enregistrerBTN = new javax.swing.JButton();
        TypeCB = new javax.swing.JComboBox<>();
        numeroPermisLabel1 = new javax.swing.JLabel();
        CarburantCB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        supprimerBTN = new javax.swing.JButton();
        rechercherBTN = new javax.swing.JButton();
        modifierBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 231, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setForeground(new java.awt.Color(210, 231, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(210, 231, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 624));

        jPanel4.setBackground(new java.awt.Color(210, 231, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 84, 129), 2, true), "Informations du vehicule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        typeLabel.setText("Année:");

        marqueLabel.setText("Marque:");

        numeroPermisLabel.setText("Type:");

        emailLabel.setText("Prix location/jour:");

        prenomLabel.setText("Modèle");

        enregistrerBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        enregistrerBTN.setForeground(new java.awt.Color(16, 84, 129));
        enregistrerBTN.setText("Enregistrer");
        enregistrerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 if(marqueTF.getText().isEmpty() || prenomTF.getText().isEmpty() || telephoneTF.getText().isEmpty() || TypeCB.getSelectedItem().toString().isEmpty() || CarburantCB.getSelectedItem().toString().isEmpty() || emailTF.getText().isEmpty() ) {
                 	JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs de texte.", "Error", JOptionPane.ERROR_MESSAGE);
                 }else {
                 try {
                     Comptes.conn = backend.ConnectionManager.getConnection();
                 
                         Vehicule vehicule = new Vehicule(conn, marqueTF.getText(), prenomTF.getText(), Integer.parseInt(telephoneTF.getText()), TypeCB.getSelectedItem().toString(), CarburantCB.getSelectedItem().toString(), Integer.parseInt(emailTF.getText()));
                         populateTable();
                     
                 } catch (SQLException ex) {
                     ex.printStackTrace();
                 }
                 }
        	}
         	
         });

        TypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essence", "Diesel", "GPL", "GNV", "Electricité" }));
        TypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeCBActionPerformed(evt);
            }
        });

        numeroPermisLabel1.setText("Carburant:");

        CarburantCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "Berline" }));
        CarburantCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarburantCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeLabel)
                    .addComponent(numeroPermisLabel)
                    .addComponent(prenomLabel)
                    .addComponent(marqueLabel)
                    .addComponent(emailLabel)
                    .addComponent(numeroPermisLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(marqueTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(prenomTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(telephoneTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(emailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(TypeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CarburantCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(enregistrerBTN)
                .addGap(189, 189, 189))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marqueLabel)
                    .addComponent(marqueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLabel)
                    .addComponent(prenomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(telephoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPermisLabel)
                    .addComponent(TypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarburantCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroPermisLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(enregistrerBTN)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(210, 231, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 624));

        jPanel5.setBackground(new java.awt.Color(210, 231, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 84, 129), 2), "Vehicules enrégistrés", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 17), new java.awt.Color(16, 84, 129))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_voiture", "Marque", "Modele", "Annee", "Type", "Carburant", "Prix/jr", "Etat"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(16, 84, 129));
        jScrollPane1.setViewportView(jTable1);

        supprimerBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        supprimerBTN.setForeground(new java.awt.Color(16, 84, 129));
        supprimerBTN.setText("Supprimer");
        supprimerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBTNActionPerformed(evt);
            }
        });

        rechercherBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        rechercherBTN.setForeground(new java.awt.Color(16, 84, 129));
        rechercherBTN.setText("Rechercher");
        rechercherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherBTNActionPerformed(evt);
            }
        });

        modifierBTN.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        modifierBTN.setForeground(new java.awt.Color(16, 84, 129));
        modifierBTN.setText("Modifier");
        modifierBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(rechercherBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(modifierBTN)
                .addGap(83, 83, 83)
                .addComponent(supprimerBTN)
                .addGap(85, 85, 85))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supprimerBTN)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rechercherBTN)
                        .addComponent(modifierBTN)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rechercherBTNActionPerformed(ActionEvent evt) {
        new searchVehicule(this, conn).setVisible(true);
    }

    private void modifierBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBTNActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        Object value = jTable1.getValueAt(selectedRow, 0);
        new ModifyVehicule(this, conn, Integer.parseInt(value.toString())).setVisible(true);
    }//GEN-LAST:event_modifierBTNActionPerformed

    private void supprimerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBTNActionPerformed
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();

        // Check if a row is selected
        if (selectedRow != -1) {
            // Get the value in the first column (index 0) of the selected row
            Object value = jTable1.getValueAt(selectedRow, 0);

            // Display a confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this vehicule?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            // If user confirms deletion
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    int id = Integer.parseInt(value.toString());
                    Vehicule.deleteVehicule(conn, id);
                    populateTable(); // Refresh the table
                    JOptionPane.showMessageDialog(this, "Vehicule deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error deleting vehicule: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Warn the user to select a row
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a user to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_supprimerBTNActionPerformed

    private void TypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeCBActionPerformed

    private void enregistrerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerBTNActionPerformed
        
    }//GEN-LAST:event_enregistrerBTNActionPerformed

    private void CarburantCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarburantCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarburantCBActionPerformed

    public void populateTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data
        try {
            Connection conn = backend.ConnectionManager.getConnection();
            String query = "SELECT * FROM Vehicule";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_vehicule"),
                    rs.getString("marque"),
                    rs.getString("modele"),
                    rs.getInt("annee"),
                    rs.getString("type"),
                    rs.getString("carburant"),
                    rs.getInt("prix_location_jour"),
                    rs.getString("etat")
                };
                model.addRow(row);
            }
            System.out.println("Table populated successfully!");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void populateTableFromArrayList(ArrayList<Vehicule> vehicules) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data

        for (Vehicule vehicule : vehicules) {
            Object[] row = {
            		vehicule.getIdVehicle(),
            		vehicule.getMarque(),
            		vehicule.getModele(),
            		vehicule.getAnnee(),
            		vehicule.getType(),
            		vehicule.getCarburant(),
            		vehicule.getPrixLocationJour(),
            		vehicule.getEtat()
            };
            model.addRow(row);
        }
        System.out.println("Table populated successfully!");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CarburantCB;
    private javax.swing.JComboBox<String> TypeCB;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton enregistrerBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel marqueLabel;
    private javax.swing.JTextField marqueTF;
    private javax.swing.JButton modifierBTN;
    private javax.swing.JLabel numeroPermisLabel;
    private javax.swing.JLabel numeroPermisLabel1;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField prenomTF;
    private javax.swing.JButton rechercherBTN;
    private javax.swing.JButton supprimerBTN;
    private javax.swing.JTextField telephoneTF;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
